## Probando Numpy y Pandas

A continuación, se le brinda código en hojas de trucos disponibles en las herramientas Pandas y Numpy, las cuales debe probar cada código y brindar resultados por secciones, donde cada sección debe ir separada por una descripción en Markdown.

#### a. ¿Campo de aplicación de las librerías Pandas y Numpy?

NumPy es un paquete de Python que significa “Numerical Python”, es la librería principal para la informática científica, proporciona potentes estructuras de datos, implementando matrices y matrices multidimensionales. Estas estructuras de datos garantizan cálculos eficientes con matrices.

#### b. Utilizando la hoja de trucos de Numpy, pruebe cada uno de los códigos y muestre los resultados de cada sección.

### Creando Arrays

In [9]:
import numpy as np

a = np.array([1,2,3])
b = np.array([(1.5,2,3), (4,5,6)], dtype = float)
c = np.array([[(1.5,2,3), (4,5,6)], [(3,2,1), (4,5,6)]], dtype = float)


#### Marcadores de posición iniciales

In [10]:
np.zeros((3,4))               
np.ones((2,3,4),dtype=np.int16)
d = np.arange(10,25,5)
np.linspace(0,2,9)
e = np.full((2,2),7) 
f = np.eye(2)
np.random.random((2,2))
np.empty((3,2))

array([[1.39069238e-309, 1.39069238e-309],
       [1.39069238e-309, 1.39069238e-309],
       [1.39069238e-309, 1.39069238e-309]])

### Guardar y cargar en disco

In [11]:
np.save('my_array', a)
np.savez('array.npz', a, b)
np.load('my_array.npy')


array([1, 2, 3])

### Guardar y cargar archivos de texto

In [12]:
np.loadtxt("myfile.txt")
np.genfromtxt("my_file.csv", delimiter=',')
np.savetxt("myarray.txt", a, delimiter=" ")


OSError: myfile.txt not found.

### Tipos de datos

In [13]:
np.int64  
np.float32
np.complex
np.bool
np.object
np.string_
np.unicode_

numpy.str_

### Inspección de su matriz

In [14]:
a.shape  
len(a)
b.ndim
e.size
b.dtype   
b.dtype.name       
b.astype(int)

array([[1, 2, 3],
       [4, 5, 6]])

### Pidiendo ayuda

In [15]:
import numpy
np.info(np.ndarray.dtype)


Data-type of the array's elements.

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>


### Arrays matematicos y Operaciones Aritmeticas

In [24]:
 g = a - b ##sustraccion
([[-0.5, 0. , 0. ],
 [-3. , -3. , -3. ]])

np.subtract(a,b) 

b + a ##Adicion de arrays
([[ 2.5, 4. , 6. ],
[ 5. , 7. , 9. ]])
np.add(b,a) 

a / b ##Division
([[ 0.66666667, 1. , 1. ],
[ 0.25 , 0.4 , 0.5 ]])
np.divide(a,b)

a * b ##Multiplication
([[ 1.5, 4. , 9. ],
[ 4. , 10. , 18. ]])
np.multiply(a,b)

np.exp(b) ##Exponenciacion

np.sqrt(b) ## raiz cuadrada

np.sin(a) ##imprimir senos de una matriz

np.cos(b) ##coseno de elementos

np.log(a) ##logaritmo natural por elementos
    
e.dot(f) ##Dot product
([[ 7., 7.],
[ 7., 7.]])




[[7.0, 7.0], [7.0, 7.0]]

### Comparación

In [29]:
a == b 


array([[False,  True,  True],
       [False, False, False]])

In [30]:
a < 2 

array([ True, False, False])

In [32]:
 np.array_equal(a, b) 


False

### Funciones agregadas

In [33]:
a.sum()

6

In [47]:
a.min() ### Valor mínimo de arreglo

1

In [46]:
b.max(axis=0) ### Valor máximo de una fila de matriz

array([4., 5., 6.])

In [36]:
a.mean() 

2.0

In [39]:
np.median(b)

3.5

In [41]:
np.corrcoef(a) ### Coeficiente de correlación

1.0

In [43]:
np.std(b) ### desviacion standard

1.5920810978785667

In [45]:
b.cumsum(axis=1) ### Suma acumulativa de los elementos

array([[ 1.5,  3.5,  6.5],
       [ 4. ,  9. , 15. ]])

### Copiar Arrays

In [48]:
h = a.view()

In [49]:
np.copy(a)

array([1, 2, 3])

In [50]:
h = a.copy()

### Ordenación de Arrays

In [51]:
a.sort()

In [52]:
c.sort(axis=0)

### Subconjunto, rebanado, indexación

#### Subconjunto

In [58]:
a[2] ### Seleccione el elemento en el segundo índice

3

In [57]:
b[1,2] ### Seleccione el elemento en la fila 1, columna 2 (equivalente a b [1] [2])

6.0

#### Rebanar

In [60]:
a[0:2] ### Seleccionar elementos en el índice 0 y 1

array([1, 2])

In [61]:
b[0:2,1] ### Seleccionar elementos en las filas 0 y 1 en la columna 1

array([2., 5.])

In [62]:
b[:1] ### Seleccionar todos los elementos de la fila 0 (equivalente a b [0: 1,:])

array([[1.5, 2. , 3. ]])

In [63]:
c[1,...] ### La misma que [1,:,:]

array([[3., 2., 3.],
       [4., 5., 6.]])

In [64]:
a[ : :-1] ### Matriz invertida a

array([3, 2, 1])

#### Indexación booleana

In [65]:
a[a<2] ### Seleccione elementos de menos de 2

array([1])

#### Indexación elegante

In [66]:
b[[1, 0, 1, 0],[0, 1, 2, 0]] ### Seleccione los elementos (1,0), (0,1), (1,2) y (0,0)

array([4. , 2. , 6. , 1.5])

In [67]:
b[[1, 0, 1, 0]][:,[0,1,2,0]] ### Seleccione un subconjunto de filas y columnas de la matriz.

array([[4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5],
       [4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5]])

### Manipulación de Arrays

#### Transposición de matriz

In [68]:
i = np.transpose(b)

In [69]:
i.T

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

#### Cambiar la forma del Array

In [70]:
b.ravel()

array([1.5, 2. , 3. , 4. , 5. , 6. ])

In [71]:
g.reshape(3,-2)

array([[-0.5,  0. ],
       [ 0. , -3. ],
       [-3. , -3. ]])

#### Agregar / eliminar elementos

In [72]:
h.resize((2,6))

In [73]:
np.append(h,g)

array([ 1. ,  2. ,  3. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
        0. , -0.5,  0. ,  0. , -3. , -3. , -3. ])

In [74]:
np.insert(a, 1, 5)

array([1, 5, 2, 3])

In [75]:
np.delete(a,[1])

array([1, 3])

#### Combinando Array

In [76]:
np.concatenate((a,d),axis=0)

array([ 1,  2,  3, 10, 15, 20])

In [77]:
np.vstack((a,b))

array([[1. , 2. , 3. ],
       [1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [78]:
np.r_[e,f]

array([[7., 7.],
       [7., 7.],
       [1., 0.],
       [0., 1.]])

In [79]:
np.hstack((e,f))

array([[7., 7., 1., 0.],
       [7., 7., 0., 1.]])

In [80]:
np.column_stack((a,d))

array([[ 1, 10],
       [ 2, 15],
       [ 3, 20]])

In [81]:
np.c_[a,d]

array([[ 1, 10],
       [ 2, 15],
       [ 3, 20]])

### División de matrices

In [83]:
np.hsplit(a,3) ### Divida la matriz horizontalmente en el tercer índice

[array([1]), array([2]), array([3])]

In [84]:
np.vsplit(c,2) ### Divida la matriz verticalmente en el segundo índice

[array([[[1.5, 2. , 1. ],
         [4. , 5. , 6. ]]]),
 array([[[3., 2., 3.],
         [4., 5., 6.]]])]

### Fin.